// <auto-generated />
using System;
using Lab2;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lab2.Migrations
{
    [DbContext(typeof(Exchanges))]
    [Migration("20260408105919_ini654")]
    partial class ini654
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("Lab2.Currency_exchange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("From_Currency_id")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Rate")
                        .HasColumnType("TEXT");

                    b.Property<int>("To_Currency_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("From_Currency_id");

                    b.HasIndex("To_Currency_id");

                    b.ToTable("Exchanges_rates");
                });

            modelBuilder.Entity("Lab2.currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("USD_rate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("Lab2.Currency_exchange", b =>
                {
                    b.HasOne("Lab2.currency", "FromCurrency")
                        .WithMany("RatesFrom")
                        .HasForeignKey("From_Currency_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lab2.currency", "ToCurrency")
                        .WithMany("RatesTo")
                        .HasForeignKey("To_Currency_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromCurrency");

                    b.Navigation("ToCurrency");
                });

            modelBuilder.Entity("Lab2.currency", b =>
                {
                    b.Navigation("RatesFrom");

                    b.Navigation("RatesTo");
                });
#pragma warning restore 612, 618
        }
    }
}
